/**
 * Cmcc_mas_wbs_PortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package org.csapi.www.service;

public interface Cmcc_mas_wbs_PortType extends java.rmi.Remote {
    public org.csapi.www.schema.ap.APRegistrationRsp APRegistration(org.csapi.www.schema.ap.APRegistrationReq APRegistrationReq) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public org.csapi.www.schema.ap.APStatusRepRsp APStatusRep(org.csapi.www.schema.ap.APStatusRepReq APStatusRepReq) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public org.csapi.www.schema.ap.APLogOutRsp APLogOut(org.csapi.www.schema.ap.APLogOutReq APLogOutReq) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public org.csapi.www.schema.ap.PauseAPRsp pauseAP(org.csapi.www.schema.ap.PauseAPReq pauseAPReq) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public org.csapi.www.schema.ap.RecoveryAPRsp recoveryAP(org.csapi.www.schema.ap.RecoveryAPReq recoveryAPReq) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public org.csapi.www.schema.ap.APSvcAuthenticRsp APSvcAuthentic(org.csapi.www.schema.ap.APSvcAuthenticReq APSvcAuthenticReq) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public void APSvcPerfCmd(org.csapi.www.schema.ap.APSvcPerfCmdReq APSvcPerfCmdReq) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public org.csapi.www.schema.ap.AlarmRsp APSvcAlarm(org.csapi.www.schema.ap.AlarmReq alarmReq) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public void APSvcPerfReport(org.csapi.www.schema.ap.APSvcPerfReportReq APSvcPerfReportReq) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public void startNotification(org.csapi.www.schema.notification.StartNotificationRequest startNotificationRequest) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public void stopNotification(org.csapi.www.schema.notification.StopNotificationRequest stopNotificationRequest) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public org.csapi.www.schema.sms.SendSmsResponse sendSms(org.csapi.www.schema.sms.SendSmsRequest sendSmsRequest) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public void notifySmsDeliveryStatus(org.csapi.www.schema.sms.NotifySmsDeliveryStatusRequest notifySmsDeliveryStatusRequest) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public org.csapi.www.schema.sms.SMSMessage[] getReceivedSms(org.csapi.www.schema.sms.GetReceivedSmsRequest getReceivedSmsRequest) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public org.csapi.www.schema.sms.DeliveryInformation[] getSmsDeliveryStatus(org.csapi.www.schema.sms.GetSmsDeliveryStatusRequest getSmsDeliveryStatusRequest) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public void notifySmsReception(org.csapi.www.schema.sms.NotifySmsReceptionRequest notifySmsReceptionRequest) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public org.csapi.www.schema.mms.SendMessageResponse sendMessage(org.csapi.www.schema.mms.SendMessageRequest sendMessageRequest) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public org.csapi.www.schema.mms.DeliveryInformation[] getMessageDeliveryStatus(org.csapi.www.schema.mms.GetMessageDeliveryStatusRequest getMessageDeliveryStatusRequest) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public org.csapi.www.schema.mms.MessageReference[] getReceivedMessages(org.csapi.www.schema.mms.GetReceivedMessagesRequest getReceivedMessagesRequest) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public org.csapi.www.schema.mms.GetMessageResponse getMessage(org.csapi.www.schema.mms.GetMessageRequest getMessageRequest) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public void notifyMessageReception(org.csapi.www.schema.mms.NotifyMessageReceptionRequest notifyMessageReceptionRequest) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public void notifyMessageDeliveryReceipt(org.csapi.www.schema.mms.NotifyMessageDeliveryReceiptRequest notifyMessageDeliveryReceiptRequest) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public org.csapi.www.schema.location.GetLocationResponse getLocation(org.csapi.www.schema.location.GetLocationRequest getLocationRequest) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public org.csapi.www.schema.location.LocationData[] getLocationForGroup(org.csapi.www.schema.location.GetLocationForGroupRequest getLocationForGroupRequest) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public org.csapi.www.schema.location.StartPeriodicNotificationResponse startPeriodicNotification(org.csapi.www.schema.location.StartPeriodicNotificationRequest startPeriodicNotificationRequest) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public void endNotification(org.csapi.www.schema.location.EndNotificationRequest endNotificationRequest) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public void locationNotification(org.csapi.www.schema.location.LocationNotificationRequest locationNotificationRequest) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public void locationError(org.csapi.www.schema.location.LocationErrorRequest locationErrorRequest) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public void locationEnd(org.csapi.www.schema.location.LocationEndRequest locationEndRequest) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public org.csapi.www.schema.wap.SendPushResponse sendPush(org.csapi.www.schema.wap.SendPushRequest sendPushRequest) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public org.csapi.www.schema.wap.DeliveryInformation[] getPushDeliveryStatus(org.csapi.www.schema.wap.GetPushDeliveryStatusRequest getPushDeliveryStatusRequest) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public void notifyPushDeliveryReceipt(org.csapi.www.schema.wap.NotifyPushDeliveryReceiptRequest notifyPushDeliveryReceiptRequest) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public org.csapi.www.schema.ussd.MakeUssdResponse makeUssd(org.csapi.www.schema.ussd.MakeUssdRequest makeUssdRequest) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public org.csapi.www.schema.ussd.HandleUssdResponse handleUssd(org.csapi.www.schema.ussd.HandleUssdRequest handleUssdRequest) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public org.csapi.www.schema.ussd.UssdContinueResponse ussdContinue(org.csapi.www.schema.ussd.UssdContinueRequest ussdContinueRequest) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public void endUssd(org.csapi.www.schema.ussd.EndUssdRequest endUssdRequest) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
    public void notifyUssdEnd(org.csapi.www.schema.ussd.NotifyUssdEndRequest notifyUssdEndRequest) throws java.rmi.RemoteException, org.csapi.www.schema.common.v2_0.ServiceException, org.csapi.www.schema.common.v2_0.PolicyException;
}
