health:
  message:
      festival[0]: 
        name: 世界糖尿病日
        month: 11
        day: 14
        content[0]: 今天是世界糖尿病日。为了预防糖尿病，应做到：1、早发现、早干预、早受益。2、管住嘴、迈开腿。改善生活中的不良行为，控制饮食、适量运动、戒烟限酒。3、患者家属也要同时积极预防糖尿病。
        content[1]: 今天是世界糖尿病日，糖尿病是可预防的疾病。预防糖尿病应掌握以下四点：1、学习健康知识有利于科学防治；2、不宜吃含高胆固醇的食物及动物脂肪，不宜饮酒；3、保持一定的运动量控制体重；4、保持情绪平静、心态平和。
      festival[1]:
        name: 世界睡眠日
        month: 3
        day: 21
        content[0]: 您好，今日是世界睡眠日，提倡大家每天在23点以前入睡，良好的睡眠是对疲惫了一天的身体最好的恢复，可睡前喝一杯热牛奶，助眠补钙；可温水泡脚，舒缓放松促进循环。从今天起加入我们早睡的行列吧！
        content[1]: 今天是世界睡眠日，睡个好觉，清醒生活，远离慢病。
      festival[2]:
        name: 元旦
        month: 1
        day: 1
        delay: 3
        content[0]: 新年伊始，昆山健康促进中心祝您及家人学业，一举成名，事业，一帆风顺。幸福，一生一世，全家，健康平安。
      festival[3]:
        name: 世界卫生日
        month: 4
        day: 7
        content[0]: 今天是世界卫生日。每年的4月7日为世界卫生日，昆山健康促进中心呼吁大家普及健康知识，提高健康水平；树立健康新形象，改变不良生活习惯；不吸烟，不酗酒；合理搭配膳食结构，规律用餐，保持营养平衡，维持健康体重；保持良好的心理状态，自信乐观，喜怒有度。
      festival[4]:
        name: 世界高血压日
        month: 5
        day: 17
        content[0]: 今天是世界高血压日。高血压是一种常见病，是心脑血管疾病的最重要的危险因素，被称为影响健康的“无形杀手”。今日是世界高血压日，鼓励采用上臂式电子血压计进行家庭血压监测，评估血压波动和降压疗效，同时改善不良的生活方式，达到平稳控压的效果。
      festival[5]:
        name: 世界肝炎日
        month: 7
        day: 28
        content[0]: 今天是世界肝炎日。乙肝病毒主要传播途径有母婴、血液、破损的皮肤黏膜和性接触，并不会通过共用餐具传播。疫苗接种是控制病毒传播的主要途径，建议正常人定期检查乙肝五项，表面抗体阴性时要考虑是否需要接种疫苗，乙肝患者要定期复查肝功，防止病情进展。
      festival[6]:
        name: 健康生活方式行动日
        month: 9
        day: 1
        content[0]: 全民健康生活方式行动日科普宣传：近年慢性病呈快速增长趋势，多与生活方式和行为习惯、遗传、环境、卫生保健等危险因素相关。提倡您保持健康生活方式，合理膳食、规律起居、戒烟限酒、适量运动、保证睡眠、劳逸结合，让我们一起养成易于健康的习惯吧！
      festival[7]:
        name: 世界心脏日
        month: 9
        day: 29
        content[0]: 今天是世界心脏日。在全世界范围，心血管疾病已逐渐成为威胁人类健康的“第一杀手”，设立世界心脏日旨在唤起公众对心血管病及其危险因素如高血压、肥胖、缺乏运动、吸烟等的重视。倡导：限盐减重多运动，戒烟限酒心态平，关爱心脏保健康。
      festival[8]:
        name: 国庆节
        month: 10
        day: 1
        delay: 7
        content[0]: 十一国庆至，送你十一种祝福：快乐、平安、健康、甜蜜、美丽、魅力、成功、顺利、如意、幸福，愿你事业顺利，家庭幸福，爱情甜蜜，友情永伴，平安一生，国庆快乐！
      festival[9]:
        name: 全国高血压日
        month: 10
        day: 8
        content[0]: 今天是全国高血压日。降压药使用小贴士：要长效，不短效，一天一次更重要；要规律，不随意，测完血压再吃药；要和缓，不求快，四到八周是常态；要坚持，不停药，平稳长效保心脑。
      festival[10]:
        name: 世界骨质疏松日
        month: 10
        day: 20
        content[0]: 今天是世界骨质疏松日。预防骨质疏松：保障各种营养素均衡，养成良好习惯，做到起居有常；避免久坐久卧，不剧烈运动。日常保养需根据自身状况选择合适的运动方式，以能耐受和不疲劳为宜。老年人和绝经后的妇女多有体内钙缺失情况，为补钙重点人群
      festival[11]:
        name: 世界卒中日
        month: 6
        day: 24
        content[0]: 今天是世界卒中日。积极治疗控制高血压；加强糖尿病、心脏病的治疗；适当体育锻炼；合理饮食，适量摄入动物蛋白质，如瘦肉、鱼类等；降低食盐摄入量，每天控制在 6 克以内；增加新鲜蔬菜水果，以提高钾摄入量；提倡戒烟，控制体重，杜绝不良生活方式。
      festival[12]:
        name: 中国心梗救治日
        month: 11
        day: 20
        content[0]: 11月20日是中国心梗救治日，心梗急救如能在发病120分钟内完成可大大降低病死率和致残率，取得良好的治疗效果。心梗急救常识：请牢记2个120，急性心肌梗死发生后要迅即拨打120，抢救的黄金时间为120分钟。
      festival[13]: 
        name: 世界强化免疫日
        month: 12
        day: 15
        content[0]: 世界强化免疫日，免疫预防每一日。补充营养维生素，提高免疫是要素；日日锻炼身体壮，抵抗疾病要强壮。快乐加一点，烦恼减一点，健康乘一点，疾病除一点，希望朋友多健康，生活幸福快乐多。
      lfestival[0]: 
        name: 端午节
        month: 5
        day: 5
        delay: 3
        content[0]: 端午养生有门道，分享给您请牢记，能吃能喝不健康，大吃大喝损胃肠，胡吃海喝更遭殃，会吃会喝才健康。每天睡够8小时，午间抽空打个盹，清淡饮食多蔬果，晚餐粗粮健脾胃。昆山健康促进中心祝您快乐安康！
      lfestival[1]:
        name: 中秋节
        month: 8
        day: 15
        delay: 3
        content[0]: “人逢喜事精神爽，月到中秋分外明”。中秋节期间应注重饮食平衡，营养全面，避免偏食，注意补充优质蛋白、维生素等营养素。宜多食新鲜蔬菜和水果，多喝开水、淡茶、果汁饮料、豆浆、牛奶等流质，以养阴润燥。不宜过量食用寒凉瓜果。
        content[1]: 中秋团圆日，吃月饼是我国流传已久的传统习俗，但月饼为“三高”食物，即高糖、高油、高脂肪，为了健康，建议少吃。可在正餐结束休息一段时间后，将月饼分切进食，搭配绿茶一同品味。
      lfestival[2]:
        name: 龙头节
        month: 2
        day: 2
        content[0]: 二月二龙抬头，剃龙头，享猪头。今日是农历二月初二，在这一天民间有理发、吃猪头肉的习俗。理发店洗头一般是后仰洗头，此时高血压患者不宜将脖子扭动较大范围，因为颈部向后弯曲，颈部血管阻力增大，使脑供血不足，会增加脑卒中的风险。
      lfestival[3]:
        name: 重阳节
        month: 9
        day: 9
        content[0]: “九月九日，佩茱萸，食蓬饵，饮菊花酒，云令人长寿。”今日是重阳节，又有“老人节”之称，宜安排家人团聚，共同出游赏秋、观赏菊花、吃重阳糕、饮菊花酒等。外出游玩时，注意防寒保暖，途中及时补水，不可一次饮水过多。
      lfestival[4]:
        name: 除夕
        month: 12
        day: 30
        content[0]: 除夕来到，幸福锐不可当。欢声笑语不断，欢聚一堂热闹。烦恼忧伤全抛，甜蜜好运常抱。福运安康顺畅，健康快乐到老。昆山健康促进中心祝您除夕幸福享团圆!
      lfestival[5]:
        name: 春节
        month: 1
        day: 1
        delay: 7
        content[0]: 拜个年，欢欢喜喜过新年；风调雨顺平安年，吉祥如意健康年；财源广进发财年，梦想成真成功年；五谷丰登丰收年，祝您美满幸福年!
        content[1]: 过大年，放鞭炮；团圆饭，好味道；人团圆，喜气闹；家安乐，福气报；睡眠足，精神爽；清淡食，消化良；平安符，家里罩；祝福您，永健康。
        content[2]: 春节到，忙奔走，走亲访友别累着。聚餐多，酒菜好，切莫贪杯酒喝高。娱乐多，锻炼少，多做运动身体好。笑容多，烦恼少，心情舒畅睡眠好。昆山健康促进中心祝您新年好！
        content[3]: 新春佳节团圆会，健康饮食最可贵。多吃粗粮调肠胃，多喝淡茶解油腻。多吃蔬菜促消化，适当运动心情好。适当运动防腰酸，保持微笑心乐观。愿您健康长相伴，快乐幸福不间断。
        content[4]: 狗年财气旺不停，财旺人旺运气旺。健康快乐常伴您，幸福美满粘着您。昆山健康促进中心祝您春节快乐！
        content[5]: 新春佳节欢乐多，身心健康最重要。饮酒适量为原则，饮食规律好处多。荤素搭配七分饱，清淡食物不油腻。大鱼大肉要减少，睡眠充足精神好。昆山健康促进中心祝您春节快乐！
      lfestival[6]:
        name: 小年
        month: 12
        day: 24
        content[0]: 今天是小年。浓浓快乐做糖浆，填上好运做成灶糖。伴着小年来歌唱，悄无声息到您身旁。心意送上定要尝，只为健康将您黏上。昆山健康促进中心祝您小年快乐！
      solar[0]:
        name: 立夏
        month: 5
        day: 5
        delay: 15
        content[0]: 立夏节气后，气温升高，人体出汗明显增多，多喝水可有效避免血液浓缩，降低血液粘稠度，应坚持每天饮水量在2000毫升左右，多吃新鲜果蔬。夏季日长夜短，中午适当午睡有益健康。气温升高还会引起血管扩张，定期监测血压必不可少。
        content[1]: 
      solar[1]:
        name: 夏至
        month: 6
        day: 21
        delay: 15
        content[0]: 夏至始，阳极阴生，阴气居于内。饮食以清泄暑热、增进食欲为目的，多吃苦味食物，宜清补。绿叶菜和瓜果类等水分多的蔬菜水果都是不错的选择，如白菜、苦瓜、丝瓜、黄瓜等。另“冬吃萝卜，夏吃姜”，生姜对于防暑度夏也有一定益处。
      solar[2]:
        name: 白露
        month: 9
        day: 7
        delay: 15
        content[0]: “蒹葭苍苍，白露为霜。保暖补水，我更健康”。白露节气后，昼夜温差大，秋天气候干燥，人体消耗水分多，容易造成体内缺水，血液粘稠度高，血流减慢，血容量不足增加了缺血性心脑血管事件风险。因此要注意保暖、血压达标、及时补充水分。
        content[1]: 白露节气，人容易出现脾胃虚弱、消化差的症状，抵抗力也有所下降。这个时节多吃点温热的、有补养作用的粥食
      solar[3]:
        name: 霜降
        month: 10
        day: 23
        delay: 15
        content[0]: “霜降时节须进补，保健养生看食谱”。霜降节气后，饮食进补应以淡补为原则，注意补气血以养胃。宜少吃大蒜、辣椒、火锅、烧烤等辛辣刺激的食物，秋季干燥，容易上火。推荐进补粥及其他滋润的食物，例如梨、苹果、芋头、柿子、栗子等。
        content[1]: 补冬不如补霜降”，认为比起冬天的进补，霜降时节的秋补会更有效果。补物则逃不过秋天最肥硕的鸭和鲜香的羊肉，煲汤时最好还要加上党参、当归、熟地和黄芪四味中药，各有益处。
      solar[4]:
        name: 立春
        month: 2
        day: 3
        delay: 15
        content[0]: “春三月、乍暖寒；升阳气、捂为安”。立春伊始气温变化无常，大风常至，促使肝气亢盛，血压会呈现较大波动。要留心春捂，不要过早去衣；每晚用40度以内的温水泡脚半小时，可升阳固脱，促进血液循环。
        content[1]: 立春之后，饮食要清淡，不要过度食用干燥、辛辣的食物。同时，因为此时阳气上升容易伤阴，所以要特别注重养阴，可以多选用百合、山药、莲子、枸杞等食物
        content[2]: 立春之后，在作息时间上，人们也应顺应自然界的规律，早睡早起。在精神养生方面，要力戒暴怒，更忌忧郁，做到心胸开阔，保持心境愉悦
      solar[5]:
        name: 惊蛰
        month: 3
        day: 5
        delay: 15
        content[0]: “天若有情天亦老、惊蛰时节多吃枣”。惊蛰前后，气温上升，这时易出现倒春寒，会引起心血管问题。提醒您要注意保暖，同时要少吃酸，可适当食用一些具有利水祛湿、健脾补益作用的汤水或食疗粥来增强体质，如大枣粥、山药粥等。
        content[1]: 惊蛰时节，乍暖还寒，气候比较干燥，很容易使人口干舌燥、外感咳嗽。我国民间素有惊蛰日吃梨的习俗
        content[2]: 惊蛰时节阳气大动，可以多伸懒腰来解乏、醒神、活动肢体； 
      solar[6]:
        name: 冬至
        month: 12
        day: 21
        delay: 15
        content[0]: 冬至养生六原则：“定时起居有规律，添衣保暖防低温，运动增强抵抗力，对症药补遵医嘱，科学食补以温肾，心态平和常感恩”。针对科学食补原则，推荐热量高、营养丰富、易消化的食物。冬至有着北方吃饺子、南方吃汤圆的习俗，请适量食用。
        content[1]: 冬至时节天气寒冷，人体需要足够的能量来抵御寒冷，而肉类含有丰富的蛋白质、碳水化合物和脂肪，有补气活血，温中暖下的功效，是进补的佳品
        content[2]: 冬至前后睡好“子午觉”在养生学中具有重要地位，除了保证夜间睡眠，午饭后可适当打个盹，但要避免睡时着凉。
      solar[7]:
        name: 春分
        month: 3
        day: 20
        delay: 15
        content[0]: “雨霁风光，春分天气。千花百卉争明媚”。春分后万物复苏，人体血液及激素也正处于旺盛时期，易发高血压。春分时节高血压患者应预防便秘。春分养生饮食宜清淡，适当多吃一些养阴润燥的食物，如梨、大枣、百合、银耳等。
        content[1]: 春分时节，日夜温差较大，不时会有寒流侵袭，阴雨连绵。穿衣可以下厚上薄，注意下肢及脚部保暖，最好能够微微汗出，以散去冬天潜伏的寒邪。
        content[2]: 春分时节，肝气旺，肾气微，饮食方面要注意健运脾胃，健脾祛湿。可多吃姜、葱、荞、韭菜、淮山、枸杞、土豆、椰菜、鸡肉、鲤鱼、鲫鱼等，也可结合药膳进行调理。
        content[3]: 春分时节，人体气血要保持平衡，运动时间尽量在早晨，不要在睡前1小时内，夜晚过度运动令人兴奋影响睡眠。若只能在晚上运动，尽量选择散步、瑜伽、体操这类运动量小的活动。出汗后不要吹风，尽快擦干
      solar[8]:
        name: 谷雨
        month: 4
        day: 19
        delay: 15
        content[0]: 谷雨后，春尽、夏至。饮食应注意：1.食盐每天少于6克，钠摄入过高会诱发高血压。2.每天摄入脂肪少于总热量的30%。3.少食添加到食品中的果糖，白砂糖等。4.少吃动物食品，因为胆固醇过高会导致动脉硬化诱发心脏及脑血管疾病。
        content[1]: 谷雨前后正是香椿上市时节，有"雨前香椿嫩如丝"之说。可以香椿拌豆腐、香椿煎鸡蛋，用切成段的嫩芽、摊成薄皮的鸡蛋相拌卷等。
      solar[9]:
        name: 小暑
        month: 7
        day: 7
        delay: 15
        content[0]: “冬不坐石，夏不坐木”。小暑过后，气温高、湿度大。久置露天里的木料，如椅凳等，经过露打雨淋，含水分较多，表面看上去是干的，经太阳一晒，温度升高，便会向外散发潮气，久坐能诱发痔疮、风湿和关节炎等疾病。尤其是中老年人，一定要注意哦！
        content[1]: 小暑之后，夜卧早起，每天最好5、6点起床活动。若起床太晚，体内的阳气没法得以舒展，郁结体内，容易上火、身体疲乏。郁久化酸，易损伤肾脏，引发心脑血管疾病、肥胖、高血压等。
      solar[10]:
        name: 立冬
        month: 11
        day: 7
        delay: 15
        content[0]: 立冬开始。寒冷气候会造成人体热量散失过多，影响内分泌系统，从而激发肌体的御寒能力。因此，立冬时节的营养应以增加热能为主，可适当补充瘦肉、鸡蛋、鱼类、乳类、豆类等优质蛋白和富含碳水化合物和脂肪的食物。
      solar[11]:
        name: 小雪
        month: 11
        day: 22
        delay: 15
        content[0]: “久雨重阳後，清寒小雪前。保暖配保健，防止疾病来”。小雪过后，天气更冷，高血压、心脑血管疾病进入复发的高峰期，所以中老年人一定要注意保暖，做好冬季保健，多吃一些温性食物，在平时的菜肴中，可以多加入一些葱、姜、蒜等作料。
        content[1]: 小雪之后应适当远离远离生冷寒凉的食物，可以备一些姜枣茶祛风散寒
      solar[12]:
        name: 雨水
        month: 2
        day: 18
        delay: 15
        content[0]: 雨水节气中，地湿之气渐升，且早晨时有露、霜出现。饮食调养应侧重于调养脾胃和祛风除湿。又由于此时气候较阴冷，可以适当地进补，如蜂蜜、大枣、山药、银耳等
        content[1]: 雨水节气中仍然较为寒冷,不宜于做过于激烈运动,避免因为体内能量(中气)消耗太过导致肝气一下子往外跑得太多而出现发热、上火等症状。可以做些散步、打太极拳等较轻松的运动。
        content[2]: 雨水节气,气候转暖,早晚较冷,风邪渐增,常见口舌干燥现象,我们宜多吃新鲜蔬菜、水果,以补充人体水分,少食油腻之品。
      solar[13]:
        name: 清明
        month: 4
        day: 4
        delay: 15
        content[0]: 清明时节雨多湿气较重，在饮食上要注意选择一些温胃祛湿的食物，如白菜、萝卜、芋头等。
        content[1]: 中医认为，清明时节正值肝阳上升时节，故不宜进食竹笋、咸菜、鸡、海鱼等“发物”。有慢性病的人要忌食。
        content[2]: 清明时期，万物抽芽，百花吐蕊，花香四溢，过敏性体质的人更易皮肤过敏.尊麻疹、过敏性鼻炎、哮喘病等，也都是这个节气的高发病.这时应在医生指导下，服用抗过敏的中药及维生素C等，如出现气粗、呼吸困难的要立即就医。     
      solar[14]:
        name: 小满
        month: 5
        day: 20
        delay: 15
        content[0]: 小满时节天气逐渐炎热，衣着更应简单凉爽，才有利于汗液和热量的疏散。有些年轻女孩们喜欢穿露脐装、短背心等，此时建议最好选择纯棉布料，因为棉料更容易吸收人体汗液
      solar[15]:
        name: 大暑
        month: 7
        day: 22
        delay: 15
        content[0]: 大暑时节，天气炎热，雷电、暴雨多，此时人们容易受暑湿影响出现腹胀、食欲下降、乏力等症状，此时饮食宜清淡多样，以补气健脾、消暑生津为主，可多食绿豆、黄瓜、苦瓜、莲藕、鸭肉、冬菇、紫菜、白茅根等食物及药食两用之品。
        content[1]: 大暑正处于“三伏天”，天气炎热，此时宜少运动或选择低强度的运动项目，如散步、快步走、八段锦、太极拳等，宜在清晨或傍晚在清凉的公园、河边、林荫道旁进行。
      solar[16]:
        name: 处暑
        month: 8
        day: 22
        delay: 15
        content[0]: 处暑后的初秋是“冷”并没有感觉到“寒”，“皮肉之冷”是可以忍耐的，而采取“秋冻”对于适应与抗御后来冬天的严寒都有很大的好处，从机体适应能力上看，也可以说符合季节之间的“惯性原理”
      solar[17]:
        name: 秋分
        month: 9
        day: 22
        delay: 15
        content[0]: 秋分时节的鲜梨、萝卜都具有行气的功效，可以抵达人体各处润燥。梨尽量熟食，可滋五脏之阴。秋燥易伤大肠，所以经常有便秘、痔疮等出现，此时应多食芭蕉、香蕉、芝麻、核桃与何首乌等。
      solar[18]:
        name: 寒露
        month: 10
        day: 7
        delay: 15
        content[0]: 寒露之后，早餐应吃温食，最好喝热药粥，因为粳米、糯米均有极好的健脾胃、补中气的作用，像甘蔗粥、玉竹粥、沙参粥、生地粥、黄精粥等。中老年人和慢性患者应多吃些红枣、莲子、山药、鸭、鱼、肉等食品
        content[1]: 寒露以后，在气温下降和空气干燥时，感冒病毒的致病力增强。此时很多疾病的发生会危及老年人的生命，其中最应警惕的是心脑血管病
        content[2]: 寒露时节，由于秋高气爽，应该做一些贴近大自然的舒缓运动，如快步走、爬山等，既能收敛心神看，也可达到锻炼的目的。
      solar[19]:
        name: 大雪
        month: 12
        day: 7
        delay: 15
        content[0]: 大雪时节之后，接受阳光照射相对较少,人体血清素水平较低,容易导致冬季抑郁症。一项研究发现,燕麦片等全谷食物有助于保持身体血清素水平,预防抑郁。另外,糙米和水果也有助于改善情绪。
        content[1]: 大雪时节之后，起居调养宜早眠早起,并要收敛神气,保持肺气清肃。早晚温差悬殊,老年人要谨慎起居,适当运动,增强对气候变化的适应能力。
      solar[20]:
        name: 小寒
        month: 1
        day: 5
        delay: 15
        content[0]: 小寒时节之后，最好不要在出门前、睡觉前洗头。如果实在需要洗，那洗后应马上擦干或是用电吹风吹干头发，这样既能保证清洁卫生，又可以防止湿气在头上滞留导致受寒
      solar[21]:
        name: 大寒
        month: 1
        day: 19
        delay: 15
        content[0]: 大寒时节，建议养成晚上睡前热水泡脚的习惯。脚被称作人体的第二心脏，冬季寒冷，可常做足浴，暖身同时又放松身心。
        content[1]: 大寒之后，天气寒冷，空气凉而燥，最易引发鼻炎，可晨起凉水搓鼻，促进鼻黏膜血液循环。
      season[0]:
        name: 春季
        content[0]: 春季气温变化无常，大风常至，促使肝气亢盛，血压会呈现较大波动。要留心春捂，不要过早去衣；每晚用40度以内的温水泡脚半小时，可升阳固脱，促进血液循环。
        content[1]: 春季应合理饮食-清淡为宜，夜卧早起-调养精神，运动适量-循序渐进。
      season[1]:
        name: 夏季
        content[0]: 夏季气温升高，人体出汗明显增多，多喝水可有效避免血液浓缩，降低血液粘稠度，应坚持每天饮水量在2000毫升左右，多吃新鲜果蔬。夏季日长夜短，中午适当午睡有益健康。气温升高还会引起血管扩张，定期监测血压必不可少。
        content[1]: 夏季养心补心，除了多吃清淡食物，还应多吃些赤色或苦味食物，以养心安神，如小枣、莲子、百合等，这些都能起到养心安神的作用。
        content[2]: 夏季蔬菜水果相对比较多，在保证清洁卫生的条件下能生吃的尽量生吃.如果想增加食欲，可以适当吃点苦味的食物，苦味食物不仅有清火的作用，同时淡淡的苦味还能增进食欲，有健胃的作用
        content[3]: 夏季各类关节痛及肢体麻木的患者最好不要穿短衣裤，不要洗冷水浴或游泳，禁睡地板以及在室外露宿，避免风寒湿气伏积于经络之中。
      season[2]:
        name: 秋季
        content[0]: 秋季是人体阳消阴长的过渡时期，要顺应自然特性来养生，早睡早起收养肺气。饮食上少吃葱姜蒜等燥热的食物，避免发散泻肺；适当多吃些生津润肺的食物，如百合、银耳、秋梨等。秋季天高气爽，可根据个人情况进行锻炼，如爬山、太极拳、游泳等。
        content[1]: 进入秋季以后，气温逐渐降低，如果大量吃生瓜果，会造成体内湿邪过盛，对脾胃产生不良的影响，引发腹部疼痛、腹泻、痢疾等胃肠道疾病。
        content[2]: 秋季之后，保证充足睡眠，注意补充水分，多吃新鲜蔬菜和水果，不要长时间待在空调房里，以免因室内外温差过大引起“热伤风”。外出时，记得随身备好藿香正气、人丹等防暑用品，同时做好防晒工作
        content[3]: 秋天人体皮肤易干燥、脱屑，贴身衣服应定期换洗。手足保养上，要保持双脚干爽。老年人不要穿硬底鞋，鞋要宽松些，袜子要透气护肤
      season[3]:
        name: 冬季
        content[0]: 冬季寒冷气候会造成人体热量散失过多，影响内分泌系统，从而激发肌体的御寒能力。因此，冬天的营养应以增加热能为主，可适当补充瘦肉、鸡蛋、鱼类、乳类、豆类等优质蛋白和富含碳水化合物和脂肪的食物。
        content[1]: 冬季养生可适当动筋骨，动静结合出点汗，才能强身体。但是需要注意，跑步做操只宜微微似汗出为度，汗多泄气，有悖于冬季阳气伏藏之道。
        content[2]: 寒冷天气使人对体内蛋氨酸的需求量增大。蛋氨酸可以通过转移作用，提供一系列适应寒冷所必需的甲基。因此，冬季应多摄取含蛋氨酸较多的食物。如芝麻、葵花子、乳制品、酵母、叶类蔬菜等。